### PR TITLE
Added Discord logo

### LINKED ISSUE #376: Add Discord invite link embedded in a logo in Readme
Discord Link: https://discord.gg/KrkbmCSZVQ

Add a Discord  logo after the "Quality over Quantity" line in readme and embed this link in it

### PR DESCRIPTION
**Pull request by 2201monesh**
Updated the readme file and added the discord logo with the given discord invite link.

<hr>

## Description 📜

- Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
- Fixes #376

<hr>

## Domain of Contribution 📊

- [ x] Others
<hr>

## Checklist ✅

- [x] I follow Contributing Guidelines & Code of conduct of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by 2201monesh** [comment]
Hey can you please give it a hacktoberfest label.

**Comment by TechSpiritSS** [comment]
I am not sure I can give Hacktober fest label on one line change
@ron2111 will review this one

**Review by ron2111 — CHANGES_REQUESTED** [review]
Just add a line in bold : 
"Join our {{discord logo made by u}} for all the discussions & updates regarding this repo."

Will give u the label 👍

**Comment by 2201monesh** [comment]
@ron2111 sure working on it

**Comment by 2201monesh** [comment]
Changes done have a look.

**Pull request closed without merging**
